## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('WimaxApp', ['core', 'simulator', 'node'])
    module.source = [
        'wimax-app.cc',	
        ]
   
    headers = bld.new_task_gen('ns3header')
    headers.module = 'WimaxApp'
    headers.source = [
        'wimax-app.h',
        ]

