## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('DvbhApp', ['core', 'simulator', 'node'])
    module.source = [
        'Dvbh-app.cc',
	
        ]
   
    headers = bld.new_task_gen('ns3header')
    headers.module = 'DvbhApp'
    headers.source = [
        'Dvbh-app.h',
	
        ]

