## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('CAMrecv', ['node'])
    module.source = [
        'CAM-recv.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'CAMrecv'
    headers.source = [
        'CAM-recv.h',
        ]

