## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('CAMsend', ['core', 'simulator', 'node'])
    module.source = [
        'CAM-send.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'CAMsend'
    headers.source = [
        'CAM-send.h',
        ]

